version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-225-113-7.compute-1.amazonaws.com
            database: dbvohrbr950ie8
            user: xdhjvpdudzrnfy
            password: ba9c3139f1f546e6ed554d1dc3cc42e2b8b79fe6aa4abe14bd94f2f35233b372
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true